'use strict';

const CARDS = [
  // — Geral —
  'Quem pede o prato mais caro do cardápio e se faz de desentendido na hora de dividir a conta?',
  'Um de nós se faz de bobo, mas está secretamente ressentido pelo resultado de outra carta. Quem?',
  'Atropelamos alguém. Quem sugere fugir do local?',
  'Em todo grupo de amigos tem alguém que se veste horrivelmente mal. No nosso é...',
  'Quem de nós é secretamente um supervilão?',
  'Quem de nós é na verdade um robô?',
  'Quem de nós pede dinheiro emprestado sabendo que nunca vai devolver?',
  'Jamais tocaria na roupa íntima de...',
  'Elegem todos nós como senadores. Quem ganha mais dinheiro cobrando propina?',
  'Quem vai se casar com alguém que ainda nem nasceu?',
  'Quem faz xixi na piscina?',
  'Quem tem mais chances de ir preso por um crime que não cometeu?',
  'Ganhamos na loteria e dividimos o prêmio entre todos. Quem é o primeiro a perder tudo o que ganhou?',
  'A partir deste ano vão entregar um Nobel pela falta de higiene pessoal. Quem de nós com certeza será indicado?',
  'Viajamos todos para Las Vegas. Quem volta casado?',
  'Um de nós há 10 anos tinha um futuro muito promissor. Quem?',
  'Somos todos cúmplices de um crime e estão nos interrogando. Quem é o primeiro a quebrar e confessar?',
  'Descobrem que um de nós tem uma coleção de chicletes mastigados por seus ex. Quem?',
  'Se nos tornássemos mafiosos, quem seria o chefão?',
  'Um de nós admira secretamente o Hitler. Quem?',
  'Somos os protagonistas de um thriller de suspense. No final, quem é o assassino?',
  'Um amigo em comum precisa urgentemente de doadores de sangue. Quem diz que foi e não foi?',
  'Chegou o apocalipse zumbi. Quem morre primeiro?',
  'Com quem você se fingiria de dormindo para não ter que ouvir durante uma viagem longa?',
  'Nos inscrevemos num programa de talentos. Quem é eliminado no primeiro episódio?',
  'Escândalo! Fotos reveladoras de uma orgia de idosos. Um de nós também estava lá. Quem?',
  'Quem você nunca ia querer como chefe?',
  'Um de nós está envelhecendo pior que os outros. Quem?',
  'Num futuro próximo, um de nós vai morrer, vítima de um acerto de contas. Quem?',
  'Um de nós tem o fetiche de comer cocô. Quem?',
  'Um de nós perdeu a virgindade aos 11 anos. Quem?',
  'Nos convidam para jantar na mesa da Dona. Quem começa a discutir aos gritos com ela?',
  'Quem você nunca gostaria que adotasse um filho seu?',
  'Todos temos nossas coisas, mas um de nós é realmente imaturo para a idade. Quem?',
  'Quem se acha muito mais inteligente do que realmente é?',
  'Se todos nós vivêssemos de stand-up, quem morreria de fome primeiro?',
  'Volta o serviço militar obrigatório. Quem dá um tiro no próprio pé pra não ir?',
  'Você tem que dar um soco na cara de um de nós. Em quem?',
  'Quem de nós se acha melhor que todos os outros?',
  'De um dia pro outro, o mundo fica sem internet. Quem surta primeiro?',
  'Somos os biólogos mais capazes do planeta. Quem inventa um vírus pra depois vender a cura?',
  'Você está numa situação complicada. De quem você não pediria conselho?',
  'Quem de nós odeia a própria vida?',
  'Quem de nós acredita que a Terra é plana?',
  'Quem de nós você não teria coragem de irritar?',
  'Quem lê a Bíblia?',
  'Vamos jogar um jogo novo. Quem demora mais pra entender as regras?',
  'Alugamos uma casa na praia e está tudo pronto. Quem cancela de última hora?',
  'Um de nós tem um filho não reconhecido. Quem?',
  'Um de nós tem uma vida dupla. Quem?',
  'Acabamos de saber de um segredo enorme! Quem é o primeiro a contar pra todo mundo?',
  'Trabalhamos numa rede de fast food. Quem cospe na comida?',
  'No dia em que a ciência descobrir como nos dar um segundo par de genitais, quem é o primeiro da fila?',
  'Todos temos uma equipe sob nosso comando. Quem maltrata mais os funcionários?',
  'Um de nós, secretamente, deseja a morte de todos os outros. Quem?',
  'Acordamos numa ilha deserta sem nenhum alimento. Quem sugere que a gente coma um de nós?',
  'Um de nós não entende a graça desse jogo, mas ri por educação pra não ficar mal. Quem?',
  'Estamos todos em quarentena, infectados com um vírus mortal e incurável. Quem foge e causa uma epidemia?',
  'Todo mundo tem medo de entrar no carro quando quem dirige é...',
  'Escalando o Monte Everest, encontramos o Yeti. Pra nossa surpresa, ele é incrivelmente parecido com...',
  'Precisamos de alguém para comandar nossas tropas. Por favor, que não seja...',
  'Éramos apóstolos. Quem foi o Judas?',
  'Nos oferecem mil dólares por cada colherada de merda que a gente comer. Quem topa ficar rico?',
  'Somos estrelas do rock. Quem é o primeiro a morrer de overdose?',
  'Estamos num avião desgovernado e sobram paraquedas para todos, menos um. Quem é o primeiro a pegar um paraquedas e se salvar?',
  'Somos membros de um bando de foras-da-lei procurados no Velho Oeste. A cabeça de quem vale menos?',
  'Somos a nova turma de oficiais de polícia. Quem é o primeiro caso de abuso de autoridade?',
  'Quem se borrou?',
  'Você só vai poder abraçar um de nós pelo resto da vida. Quem?',
  'Fui assassinado. Quem me matou?',
  'Acho justo que se permita o casamento entre duas pessoas do mesmo gênero, pensam todos menos...',
  'Pulamos todos de paraquedas. O paraquedas de quem não abre?',
  'Um de nós, numa vida passada, foi traficante de escravos. Quem?',
  'Um de nós acha que o mundo seria melhor sem saúde pública. Quem?',
  'Somos candidatos a presidente. Quem recebe menos votos?',
  'Se todos fôssemos presidentes de um país, quem seria o primeiro a implantar a pena de morte?',
  'Um de nós não acredita na igualdade de gênero. Quem?',
  'Quem ganha uma fortuna enorme no cassino e desaparece das nossas vidas por completo?',
  'Um de nós sempre quis ser policial de choque pra poder reprimir com balas de borracha. Quem?',
  'Quem convidaria uma ex pra tomar um café e mentiria descaradamente sobre a própria vida?',
  'Voltamos de férias e um de nós está com uns quilinhos a mais. Quem faz questão de apontar isso na hora?',
  'Satanás oferece realizar todos os nossos desejos em troca da nossa alma. Quem aceita?',
  'Descobriram a fórmula da imortalidade. De quem eles negam o acesso, pro bem de toda a humanidade?',
  'Um de nós está secretamente apaixonado por outro de nós. Quem?',
  'Cada um publica um livro com sua própria autobiografia. Qual te interessa menos?',
  'Estamos na cadeia. Quem é o primeiro a se prostituir em troca de proteção?',
  'Colocam nossos rostos em cédulas de dinheiro. Quem fica com a nota de menor valor?',

  // — Adulto —
  'Quem de nós transaria com um animal?',
  'Quem de nós se masturbou mais vezes no ano passado?',
  'No histórico de pornografia de quem encontraríamos as coisas mais bizarras?',
  'Com quem de nós você JAMAIS participaria de um ménage?',
  'Um de vocês quer transar comigo. Quem?',
  'Um de nós é MUITO irresponsável na hora de se proteger durante o sexo. Quem?',
  'Um de nós já teve gonorreia, clamídia e sífilis. Quem?',
  'De agora em diante, toda vez que você tiver um orgasmo, vai ver o rosto de um de nós. Tomara que não seja o de...',
  'Por um milhão de dólares, um de nós transaria com o próprio pai ou mãe. Quem?',
  'Quem de nós JAMAIS participaria de uma orgia?',
  'Um de nós sente tesão na ideia de dormir com pessoas casadas. Quem?',
  'Um de nós se masturba pensando no(a) presidente. Quem?',
  'Já é possível a clonagem humana. Quem se clona pra poder transar consigo mesmo?',
  'Os genitais de um de nós servem de molde pra brinquedos sexuais. Os de quem?',
  'Quem é o mais egoísta na cama?',
  'Quem adoraria organizar uma orgia entre nós agora mesmo?',
  'Quem tem nojinho de fazer sexo oral?',
  'Um de nós é, secretamente, uma estrela pornô. Quem?',
  'Um de nós foi virgem por muito mais tempo do que admite. Quem?',
  'Um de nós se masturba vendo o parceiro(a) com outras pessoas. Quem?',
  'Quem teria menos culpa de dormir com a ex de um amigo?',
];

module.exports = CARDS;
