'use strict';

const CARDS = [
  'Quem esqueceria o seu aniversário?',
  'Quem contaria o seu segredo mais íntimo primeiro?',
  'Quem chegaria mais atrasado para um evento importante?',
  'Quem te daria um presente completamente inútil?',
  'Quem ficaria no celular enquanto você desabafa?',
  'Quem te venderia por um pedaço de pizza?',
  'Quem reclamaria mais durante uma viagem em grupo?',
  'Quem nunca devolveria o dinheiro que deve?',
  'Quem te daria um presente que claramente era para outra pessoa?',
  'Quem dormiria na sua festa de aniversário?',
  'Quem cancelaria planos em cima da hora com mais frequência?',
  'Quem postaria uma foto sua sem pedir permissão?',
  'Quem comeria a última fatia de pizza sem perguntar?',
  'Quem chegaria sem avisar na sua casa na hora errada?',
  'Quem mandaria mensagem só quando precisa de um favor?',
  'Quem esqueceria de te convidar para um rolê?',
  'Quem falaria mal de você pelas costas sem querer muito?',
  'Quem te ligaria às 3 da manhã por um problema fútil?',
  'Quem usaria sua roupa sem pedir emprestado?',
  'Quem largaria você sozinho(a) em uma festa estranha?',
  'Quem comeria o lanche que você guardou na geladeira?',
  'Quem te taggaria em uma foto horrível sem pedir?',
  'Quem ficaria no celular durante um jantar especial?',
  'Quem daria um spoiler do seu filme favorito?',
  'Quem te emprestaria dinheiro e depois cobraria na frente de todo mundo?',
  'Quem chegaria de convidado e ficaria mais tempo do que o combinado?',
  'Quem ignoraria suas mensagens por dias e depois agiria como se nada tivesse acontecido?',
  'Quem escolheria o parceiro(a) em vez de você toda vez?',
  'Quem colocaria uma música que só ele(a) gosta na viagem inteira?',
  'Quem te daria um conselho completamente equivocado?',
  'Quem desapareceria quando você mais precisasse de ajuda?',
  'Quem roubaria toda a coberta enquanto dorme?',
  'Quem te deixaria esperando por mais de uma hora sem avisar?',
  'Quem te convidaria para algo e depois não apareceria?',
  'Quem reclamaria de tudo durante um passeio?',
  'Quem escolheria o restaurante mais caro quando é você quem paga?',
  'Quem te interromperia no meio de uma história pra contar a própria?',
  'Quem perderia algo que te emprestou?',
  'Quem exageraria nos detalhes de uma história sobre você?',
  'Quem te acordaria cedo num fim de semana por um motivo bobinho?',
  'Quem beberia a última cerveja gelada sem oferecer?',
  'Quem tiraria uma foto sua dormindo e mandaria pro grupo?',
  'Quem fingiria não ter visto sua mensagem no grupo?',
  'Quem te daria carona mas cobriria de música alta a noite toda?',
  'Quem teria mais histórias constrangedoras suas guardadas?',
  'Quem te pediria ajuda pra se mudar mas sumisse quando fosse a sua vez?',
  'Quem repetiria a mesma história chata toda vez que bebe?',
  'Quem te abandonaria na fila do banheiro num show?',
  'Quem votaria em você nesse jogo imediatamente?',
  'Quem faria barulho enquanto você tenta dormir?',
  'Quem combinaria de dividir a conta mas calcularia errado sempre a seu favor?',
  'Quem te daria uma dica de restaurante que fechou há 6 meses?',
  'Quem te mandaria meme às 7 da manhã de sábado?',
  'Quem prometeria trazer algo e sempre esqueceria?',
  'Quem te deixaria segurando o elevador por minutos e depois nem apareceria?',
  'Quem daria like em todas as fotos do seu ex(a)?',
  'Quem convidaria todo mundo menos você para uma festa?',
  'Quem te ligaria só pra reclamar da própria vida?',
  'Quem te pedisse emprestado algo e devolvesse quebrado?',
  'Quem sempre escolheria o lugar mais inconveniente pra se sentar numa viagem?',
  'Quem apareceria na sua casa bem na hora do almoço com fome?',
  'Quem te mandaria correntes e fake news no grupo da família toda semana?',
  'Quem nunca aceitaria o combinado de hora de saída?',
  'Quem ficaria irritado(a) se você não respondesse imediatamente?',
];

module.exports = CARDS;
